### ISSUE TITLE
Label and faldo:position with same value

### ISSUE THREAD

**Issue by ljgarcia** [glycoinfo/GlycoCoO#1]
Example: https://github.com/glycoinfo/GlycoCoO/blob/master/sample/schema-1.png

Do we need an 82 label for http://example.org/Protein/P1/R/EP when we have that information already as  object for the faldo:position?

**Comment by yamadaissaku** [comment]
Thank you, i updated the label of faldo:position from "82" to "Glycosylation Site: 82".
